# amazon sales
## limpieza del dataset

### 1. Importacion de librerias y carga del dataset
* Se van a cargar las librerias pandas y numpy para el manejo de los datos
* Se va a cargar el dataset para su limpieza

In [13]:
import pandas as pd
import numpy as np
df = pd.read_csv("11. Amazon Sales.csv")

### 2. Revision incial del dataset
* Se mostrará un resumen del dataset con df.info
* Se verán las dimensiones con df.shape
* Se verá el tipo de dato con df.dtypes
* Se verán las primeras 10 filas con df.shape

In [ ]:
print(df.info())
print(df.shape)
print(df.dtypes)
display(df.head(10))

(1465, 16)
product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB
None

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹149,"₹1,000",85%,3.9,"24,871",Fast Charging & Data Sync: Solero TB301 Type-C...,"AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...","Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Sh...","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1M...","It's pretty good,Average quality,very good and...","It's a good product.,Like,Very good item stron...",https://m.media-amazon.com/images/I/31wOPjcSxl...,https://www.amazon.in/Solero-TB301-Charging-48...
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,₹176.63,₹499,65%,4.1,"15,188",It Ensures High Speed Transmission And Chargin...,"AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4...","Vivek kumar,Amazon Customer,SARTHAK,Chiranjeev...","R8E73K2KWJRDS,RSD0JTIIWQQL8,R64CRSTE9SLW1,R2FR...","Long durable.,good,Does not charge Lenovo m8 t...",Build quality is good and it is comes with 2 y...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/boAt-Micro-USB-Tangle-Fr...
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories|Accessories&Peripherals|...,₹229,₹299,23%,4.3,"30,411",1m long Type-C USB Cable|Sturdy and Durable. W...,"AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...","Pavan A H,Jayesh bagad,Shridhar,rajendran,karu...","R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R...","Worth for money - suitable for Android auto,Go...",Worth for money - suitable for Android auto......,https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,₹499,₹999,50%,4.2,"1,79,691",USB WiFi Adapter —— Speedy wireless transmissi...,"AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESA...","Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akas...","R1LW6NWSVTVZ2H,R3VR5WFKUS15C5,R2F6GC79OYWUKQ,R...",Works on linux for me. Get the model with ante...,I use this to connect an old PC to internet. I...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/TP-Link-TL-WN725N-150Mbp...
9,B082LZGK39,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹299,33%,4.0,"43,994",Universal Compatibility – It is compatible wit...,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...

### 3. Eliminación de columnas irrelevantes
* Se eliminarán las columnas que no aportan al analisis de la investigación

In [15]:
columnas_a_eliminar = [
    'rating',
    'rating_count',
    'about_product',
    'user_id',
    'user_name',
    'review_id',
    'review_title',
    'review_content',
    'img_link',
    'product_link'
]

df = df.drop(columns=columnas_a_eliminar)
print("Columnas disponibles:")
print(df.columns.tolist())

Columnas disponibles:
['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage']

### 4. limpieza de los datos

* Se identifican los valores nulos del dataset

In [16]:
print("Valores faltantes por variable:")
nulos = df.isnull().sum()
porcentaje = (nulos / len(df) * 100).round(2)
resumen_nulos = pd.DataFrame({'nulos': nulos, 'porcentaje %': porcentaje})
resumen_nulos[resumen_nulos['nulos'] > 0]

Valores faltantes por variable:

Empty DataFrame
Columns: [nulos, porcentaje %]
Index: []


* Se detectan y se eliminan las filas duplicadas

In [17]:
print('Filas duplicadas:', df.duplicated().sum())
df = df.drop_duplicates()
print('Filas tras eliminar duplicados:', df.shape[0])

Filas duplicadas: 110
Filas tras eliminar duplicados: 1355

* Se eliminan los simbolos de "₹"y de ","  de `actual_price` y de `discounted_price` para convertirlas a tipo numerico
* Se eliminan los simbolos de "%"y de ","  de `discount_percentage` para convertirlo a tipo numerico

In [18]:
df["discounted_price"] = df["discounted_price"].str.replace("₹","" ).str.replace(",", "").astype(float)
df["actual_price"] = df["actual_price"].str.replace("₹","" ).str.replace(",", "").astype(float)
df["discount_percentage"] = df["discount_percentage"].str.replace("%","" ).str.replace(",", "").astype(float)

print(df[['actual_price', 'discounted_price', 'discount_percentage']].head() )

   actual_price  discounted_price  discount_percentage
0        1099.0             399.0                 64.0
1         349.0             199.0                 43.0
2        1899.0             199.0                 90.0
3         699.0             329.0                 53.0
4         399.0             154.0                 61.0

* Se recalcula el porcentaje de descuento real con los precios ya limpios

In [19]:
df["real_discount"] = ((df["actual_price"] - df["discounted_price"]) / df["actual_price"] * 100).round(2)
df["discount_percentage"] = df["real_discount"]
df = df.drop(columns=["real_discount"])

* Se divide la columna `category` por el símbolo "|" para saber como se estructura la columna

In [20]:
df["category"].str.split("|")

0       [Computers&Accessories, Accessories&Peripheral...
1       [Computers&Accessories, Accessories&Peripheral...
2       [Computers&Accessories, Accessories&Peripheral...
3       [Computers&Accessories, Accessories&Peripheral...
4       [Computers&Accessories, Accessories&Peripheral...
                              ...
1460    [Home&Kitchen, Kitchen&HomeAppliances, WaterPu...
1461    [Home&Kitchen, Kitchen&HomeAppliances, SmallKi...
1462    [Home&Kitchen, Heating,Cooling&AirQuality, Roo...
1463    [Home&Kitchen, Heating,Cooling&AirQuality, Fan...
1464    [Home&Kitchen, Kitchen&HomeAppliances, SmallKi...
Name: category, Length: 1355, dtype: object

* Se calculan los cuartiles y el rango intercuartilico para identificar  los datos atipicos

In [21]:
columnas_numericas = ["actual_price", "discounted_price", "discount_percentage"]

for col in columnas_numericas:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inf = Q1 - 1.5 * IQR
    limite_sup = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < limite_inf) | (df[col] > limite_sup)]
    
    print(col + ":", len(outliers), "outliers")

actual_price: 185 outliers
discounted_price: 210 outliers
discount_percentage: 0 outliers

* Se cambian los nombres de las columnas al español para facilitar su interpretación

In [22]:
df = df.rename(columns={
    "product_id": "id_producto",
    "product_name": "nombre_producto",
    "category": "categoria",
    "actual_price": "precio_original",
    "discounted_price": "precio_descuento",
    "discount_percentage": "porcentaje_descuento"
})
print(df.columns.tolist())

['id_producto', 'nombre_producto', 'categoria', 'precio_descuento', 'precio_original', 'porcentaje_descuento']

### 5. Revisión final
* Se hará una revision final del dataset para verificar que este correctamente limpio antes de exportarlo

In [23]:
print(df.shape)
print(df.dtypes)
print(df.info())
display(df.head(10))

(1355, 6)
id_producto              object
nombre_producto          object
categoria                object
precio_descuento        float64
precio_original         float64
porcentaje_descuento    float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
Index: 1355 entries, 0 to 1464
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_producto           1355 non-null   object
 1   nombre_producto       1355 non-null   object
 2   categoria             1355 non-null   object
 3   precio_descuento      1355 non-null   float64
 4   precio_original       1355 non-null   float64
 5   porcentaje_descuento  1355 non-null   float64
dtypes: float64(3), object(3)
memory usage: 74.1+ KB
None

,id_producto,nombre_producto,categoria,precio_descuento,precio_original,porcentaje_descuento
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.00,1099.0,63.69
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.00,349.0,42.98
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.00,1899.0,89.52
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.00,699.0,52.93
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.00,399.0,61.40
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,149.00,1000.0,85.10
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,176.63,499.0,64.60
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories|Accessories&Peripherals|...,229.00,299.0,23.41
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,499.00,999.0,50.05
9,B082LZGK39,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.00,299.0,33.44

In [24]:
df.to_csv("amazon_limpio.csv", index=False)